name: neodim_chat
description: Neodim chat
version: 0.14.0+19

environment:
  sdk: ^3.10.1
  flutter: ^3.38.3

dependencies:
  flutter:
    sdk: flutter

  http: 1.6.0
  provider: 6.1.5+1
  uuid: 4.5.2
  bubble: 1.2.1
  collection: any
  json_annotation: 4.9.0
  path_provider: 2.1.5
  intl: any
  json_view: 0.4.2
  change_case: 2.2.0
  flutter_form_builder: 10.2.0
  form_builder_validators: 11.2.0
  form_builder_extra_fields: 12.1.0
  wakelock_plus: 1.4.0
  dio: 5.9.0
  file_picker: 10.3.7

  help_page:
    git:
      url: https://github.com/z80maniac/flutter_help_page.git
      ref: c6e76a5b30a33cce197f80643fbb5f44551ee86a

dev_dependencies:
  analyzer: 9.0.0
  flutter_lints: 6.0.0
  build_runner: 2.10.4
  json_serializable: 6.11.3

flutter:
  uses-material-design: true

publish_to: "none"
